import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Sora } from "next/font/google";
import "./custom.css";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
const sora = Sora({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={sora.className}>
        {/* <header className="bg-orange-300 h-screen w-screen"> header</header> */}
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
